version: "3.9"
services:
  mysql:
    image: docker.io/mariadb:10.7.3
    ports:
      - 3306:3306
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    environment:
       MYSQL_ROOT_PASSWORD: 'root'
       MYSQL_DATABASE: 'organizer'
       MYSQL_PASSWORD: 'root'
  php:
    image: docker.io/trafex/php-nginx:2.4.0
    ports:
      - 8080:8080
    volumes:
      - "./src:/var/www/html"

