version: "3.8"
services:
  php-apache:
    container_name: php-apache
    # image: php:7.4.25-apache
    build: .

    depends_on:
      - mariadb
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Organizer
      MYSQL_USER: andrei
      MYSQL_PASSWORD: andrei
    ports:
      - 9906:3306
    volumes:
      - /opt/lampp/mysql/Organizer/organizerBackup.sql:/docker-entrypoint-initdb.d/organizerBackup.sql
